public class Driver{
 public static void main(String[]args){
   System.out.println("myIndexOf testing:");
   System.out.println(StringMethods.myIndexOf("aaaa", "b"));
   System.out.println("aaaa".indexOf("b"));
   System.out.println(StringMethods.myIndexOf("AAAA", "a"));
    System.out.println("AAAA".indexOf("a"));
   System.out.println(StringMethods.myIndexOf("This sentence does not contain the target", "z"));
    System.out.println("This sentence does not contain the target".indexOf("z"));
   System.out.println(StringMethods.myIndexOf("Testing testing", "b"));
    System.out.println("Testing testing".indexOf("b"));
   System.out.println(StringMethods.myIndexOf("something", "Something"));
    System.out.println("something".indexOf("Something"));
   System.out.println(StringMethods.myIndexOf("something", "e"));
    System.out.println("something".indexOf("e"));
   System.out.println(StringMethods.myIndexOf("aaaaaaaaaaaaa", "a"));
    System.out.println("aaaaaaaaaaaaa".indexOf("a"));
   System.out.println(StringMethods.myIndexOf("AEIOU", "U"));
    System.out.println("AEIOU".indexOf("U"));
   System.out.println(StringMethods.myIndexOf("This sentence does contain the target", "target"));
    System.out.println("This sentence does contain the target".indexOf("target"));
   System.out.println(StringMethods.myIndexOf("afkjhbawfjkakjkjfjkaz", "z"));
    System.out.println("afkjhbawfjkakjkjfjkaz".indexOf("z"));
   System.out.println("myCompareTo testing:");
   System.out.println(StringMethods.myCompareTo("a", "a"));
   System.out.println("a".compareTo("a"));
   System.out.println(StringMethods.myCompareTo("ABC", "ABC"));
   System.out.println("ABC".compareTo("ABC"));
   System.out.println(StringMethods.myCompareTo("ZERO?", "ZERO?"));
   System.out.println("ZERO?".compareTo("ZERO?"));
   System.out.println(StringMethods.myCompareTo("akfjaifaifnkalfknnkjfiwafaw", "akfjaifaifnkalfknnkjfiwafaw"));
   System.out.println("akfjaifaifnkalfknnkjfiwafaw".compareTo("akfjaifaifnkalfknnkjfiwafaw"));
   System.out.println(StringMethods.myCompareTo("testing", "testing"));
   System.out.println("testing".compareTo("testing"));
   System.out.println(StringMethods.myCompareTo("a", "b"));
   System.out.println("a".compareTo("b"));
   System.out.println(StringMethods.myCompareTo("xxx", "xxa"));
   System.out.println("xxx".compareTo("xxa"));
   System.out.println(StringMethods.myCompareTo("xx", "xxa"));
   System.out.println("xx".compareTo("xxa"));
   System.out.println(StringMethods.myCompareTo("Hello", "hello"));
   System.out.println("Hello".compareTo("hello"));
   System.out.println(StringMethods.myCompareTo("Glory to Stuyvesant!", "May the motherschool live forever!"));
   System.out.println("Glory to Stuyvesant!".compareTo("May the motherschool live forever!"));
   System.out.println("parseInt testing:");
   System.out.println(StringMethods.parseInt("123"));
   System.out.println(Integer.parseInt("123"));
   System.out.println(StringMethods.parseInt("256123"));
   System.out.println(Integer.parseInt("256123"));
   System.out.println(StringMethods.parseInt("000"));
   System.out.println(Integer.parseInt("000"));
   System.out.println(StringMethods.parseInt("2147483647"));
   System.out.println(Integer.parseInt("2147483647"));
   System.out.println(StringMethods.parseInt("1234567890"));
   System.out.println(Integer.parseInt("1234567890"));
   System.out.println(StringMethods.parseInt("-144565455"));
   System.out.println(Integer.parseInt("-144565455"));
   System.out.println(StringMethods.parseInt("-0"));
   System.out.println(Integer.parseInt("-0"));
   System.out.println(StringMethods.parseInt("-27"));
   System.out.println(Integer.parseInt("-27"));
   System.out.println(StringMethods.parseInt("-2147483648"));
   System.out.println(Integer.parseInt("-2147483648"));
   System.out.println(StringMethods.parseInt("-1234567890"));
   System.out.println(Integer.parseInt("-1234567890"));
 }
}
