public class Driver{
  public static void main(String[]args){
  	//Write your tests here!
  	Point r = new Point(100,100);
  	Point p = new Point(3.0,4.0);
  	Point q = new Point(0.0,0.0);

  	System.out.println(p+" should be (3.0,4.0)");

  	System.out.println(r.distance(p,q)+" should be 5.0");

  	p = new Point(3.0,4.0);
  	q = new Point(4.0,5.0);
  	System.out.println(p.distanceTo(q)+" should be 1.4142...");

    Point p0 = new Point(0.00, 0.00);
    Point p1 = new Point(1.00, 1.00);
    Point p2 = new Point(13.00, 1.00);
    Point p3 = new Point(13.00, 6.00);
    Point p4 = new Point(3.00, 0.00);
    Point p5 = new Point(0.00, 4.00);
    Point p6 = new Point(2, 0);
    Point p7 = new Point(1, Math.pow(3, .5));
    Point p8 = new Point(4, 0);
    Point p9 = new Point(5, 5 * Math.pow(3, .5));
    Point p10 = new Point(10, 0);
    Triangle tri0 = new Triangle(r, p, q);
    Triangle tri1 = new Triangle(p3, p1, p2);
    Triangle tri2 = new Triangle(p0, p4, p5);
    Triangle tri3 = new Triangle(2.34, 3.44, 5.72, 6.31, 9.04, 10.00);
    Triangle tri4 = new Triangle(1.00, 2.00, 3.00, 4.00, 5.00, 6.00);
    Triangle tri5 = new Triangle(1.11, 9.99, 4.00, 3.00, 0.00, 0.00);
    Triangle tri6 = new Triangle(p0, p6, p7);
    Triangle tri7 = new Triangle(p0, p5, p8);
    Triangle tri8 = new Triangle(p0, p9, p10);
    System.out.println(tri0);
    System.out.println("vertex0: " + tri0.getVertex(0));
    System.out.println("vertex1: " + tri0.getVertex(1));
    System.out.println("vertex2: " + tri0.getVertex(2));
    System.out.println("Expected: 272.947 \nOutput: " + tri0.getPerimeter());
    System.out.println(tri1);
    System.out.println("vertex0: " + tri1.getVertex(0));
    System.out.println("vertex1: " + tri1.getVertex(1));
    System.out.println("vertex2: " + tri1.getVertex(2));
    System.out.println("Expected: 30 \nOutput: " + tri1.getPerimeter());
    System.out.println(tri2);
    System.out.println("vertex0: " + tri2.getVertex(0));
    System.out.println("vertex1: " + tri2.getVertex(1));
    System.out.println("vertex2: " + tri2.getVertex(2));
    System.out.println("Expected: 12 \nOutput: " + tri2.getPerimeter());
    System.out.println(tri3);
    System.out.println("vertex0: " + tri3.getVertex(0));
    System.out.println("vertex1: " + tri3.getVertex(1));
    System.out.println("vertex2: " + tri3.getVertex(2));
    System.out.println("Expected: 18.775 \nOutput: " + tri3.getPerimeter());
    System.out.println(tri4);
    System.out.println("vertex0: " + tri4.getVertex(0));
    System.out.println("vertex1: " + tri4.getVertex(1));
    System.out.println("vertex2: " + tri4.getVertex(2));
    System.out.println("Expected: 11.314 \nOutput: " + tri4.getPerimeter());
    System.out.println(tri5);
    System.out.println("vertex0: " + tri5.getVertex(0));
    System.out.println("vertex1: " + tri5.getVertex(1));
    System.out.println("vertex2: " + tri5.getVertex(2));
    System.out.println("Expected: 22.615 \nOutput: " + tri5.getPerimeter());
    System.out.println("Triangle 0 before mutation: " + tri0);
    tri0.setVertex(0, p4);
    System.out.println("Vertex 0 becomes " + p4 + "\nAfter mutation: " + tri0);
    System.out.println("Triangle 1 before mutation: " + tri1);
    tri1.setVertex(2, p3);
    System.out.println("Vertex 2 becomes " + p3 + "\nAfter mutation: " + tri1);
    System.out.println("Triangle 2 before mutation: " + tri2);
    tri2.setVertex(1, p0);
    System.out.println("Vertex 1 becomes " + p0 + "\nAfter mutation: " + tri2);
    System.out.println("Triangle 3 before mutation: " + tri3);
    tri3.setVertex(2, p5);
    System.out.println("Vertex 2 becomes " + p5 + "\nAfter mutation: " + tri3);
    System.out.println("Triangle 4 before mutation: " + tri4);
    tri4.setVertex(0, p2);
    System.out.println("Vertex 0 becomes " + p2 + "\nAfter mutation: " + tri4);
    System.out.println("Triangle 5 before mutation: " + tri5);
    tri5.setVertex(1, p1);
    System.out.println("Vertex 1 becomes " + p1 + "\nAfter mutation: " + tri5);
    System.out.println("Expected: true, true, false, false, false, false\nOutput:");
    System.out.println(Point.closeEnough(0.00, 0.00));
    System.out.println(Point.closeEnough(2.00, 2.0000000000001));
    System.out.println(Point.closeEnough(1.78, 21389148974.23));
    System.out.println(Point.closeEnough(7.02, 3.00));
    System.out.println(Point.closeEnough(1.0, 2));
    System.out.println(Point.closeEnough(7.3, 8.9));
    System.out.println("Expected: true, true, false, false, false\nOutput:");
    System.out.println(p1.equals(p1));
    System.out.println(p0.equals(p0));
    System.out.println(p1.equals(p5));
    System.out.println(p2.equals(p0));
    System.out.println(p3.equals(p5));
    System.out.println("Expected: true, true, true, false, false\nOutput:");
    System.out.println(tri0.equals(tri0));
    System.out.println(tri2.equals(tri2));
    System.out.println(tri5.equals(tri5));
    System.out.println(tri3.equals(tri0));
    System.out.println(tri3.equals(tri4));
    System.out.println("Expected: scalene, scalene, scalene, isosceles, equilateral, equilateral\nOutput:");
    System.out.println(tri0.classify());
    System.out.println(tri1.classify());
    System.out.println(tri3.classify());
    System.out.println(tri7.classify());
    System.out.println(tri6.classify());
    System.out.println(tri8.classify());
    tri2.setVertex(1, p4);
    tri1.setVertex(2, p2);
    System.out.println("Expected: 6, 30, 2, 4.3, 13, 4.44, 1.73, 8, 43.3\nOutput: ");
    System.out.println(tri2.area());
    System.out.println(tri1.area());
    System.out.println(tri0.area());
    System.out.println(tri3.area());
    System.out.println(tri4.area());
    System.out.println(tri5.area());
    System.out.println(tri6.area());
    System.out.println(tri7.area());
    System.out.println(tri8.area());
  }
}
